---
abstract: 'Mark overload code symbols as methods'
author:
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Perl6::Junction: 0
  Test::Moose: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-MarkAsMethods
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  MooseX::MarkAsMethods:
    file: lib/MooseX/MarkAsMethods.pm
    version: 0.07
  MooseX::MarkAsMethods::MetaRole::MethodMarker:
    file: lib/MooseX/MarkAsMethods.pm
requires:
  B::Hooks::EndOfScope: 0
  Moose: 0.90
  namespace::autoclean: 0.09
resources:
  homepage: http://github.com/RsrchBoy/moosex-markasmethods/tree
  license: http://opensource.org/licenses/lgpl-license.php
  repository: git://github.com/RsrchBoy/moosex-markasmethods.git
version: 0.07
